# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-02 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('comment_favor', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_content', models.TextField()),
                ('contact_favor', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=250)),
                ('eamil', models.EmailField(max_length=254)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WebContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=0, upload_to='')),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=250)),
                ('content_auth', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('favor_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('contenttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='usertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserType'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.WebContent'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo'),
        ),
    ]
